### ISSUE TITLE
Strange error when creating a simple pie chart

### ISSUE THREAD

**Issue by mingyuan-xia** [topdmc/react-chartjs2#6]
Usage:
```js
<Chartjs2 type='pie' data={data} />
```

```
warning.js:36Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Chart`.printWarning @ warning.js:36
invariant.js:45Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Chart`.
```
looks like `lib/index.js`'s `createElement` is not working. 

using React 15.3.2, webpack, Chartjs 2.4.0

**Comment by houjiazong** [comment]
See the example [here](https://github.com/topdmc/react-chartjs2/blob/master/example/Components/Pie.jsx)

**Comment by houjiazong** [comment]
See the [example](https://github.com/topdmc/react-chartjs2/blob/master/example/Components/Pie.jsx) here

**Comment by mingyuan-xia** [comment]
Got it. I was using es2015. So it should be `<Chartjs.default type='pie' data={data} />`. Thx.
