### ISSUE TITLE
`this.chart.destroy` is not a function

### ISSUE THREAD

**Issue by jainanshul** [topdmc/react-chartjs2#7]
I am consistently getting this error when using `react-chartjs2`. Any help?

**Comment by houjiazong** [comment]
What can I do for you ?

**Comment by jainanshul** [comment]
I am not seeing this issue anymore.

**Comment by KayBeSee** [comment]
What did you do to resolve this issue @jainanshul ? I am experiencing the same thing along with charts not appearing.

**Comment by jainanshul** [comment]
I think the issue is that the examples in the project were pointing to `chart.js` that was old or may be I looked at the wrong examples. I actually moved to using `https://github.com/gor181/react-chartjs-2` and made sure I am using the latest `chart.js` node_module to solve the issue.
