### ISSUE TITLE
Async data not rerendering RC2 component

### ISSUE THREAD

**Issue by VicFrolov** [topdmc/react-chartjs2#8]
I have a class with the following render() function:

```  render() {
    this.sortMoodsLastWeek();
    return (
      <RC2 data={this.data} type="pie" />
    );
  }```

this.sortMoodsLastWeek() fetches data from our backend, and updates this.data.datasets.data.

console logging shows it is updating correctly, but it does not rerender the Pie Chart. Any suggestions?

**Comment by mario-jerkovic** [comment]
This wont work as the Chart component has the reference to the intial value of `this.data`. If you want this to work you need to re-render your component. You can do this 2 ways:

1. In `sortMoodsLastWeek ` after the data has been fetched call `this.forceUpdate` [LINK](https://facebook.github.io/react/docs/react-component.html#forceupdate)

2. set the data (backed data) into state like `this.state.data` and after the request to the backend has  finished  set the new state. This will also force the component to re-render and RC2 component will receive the new data

Hope I helped 😄

**Comment by VicFrolov** [comment]
Thanks for the post, I've actually tried both forceUpdate and setting the state, and it doesn't work with async data :(

here's what I've tried:

```
class LinearGraph extends Component {
  constructor() {
    super();
    this.state = {};
  }

  componentWillMount() {
    this.setState({ data: this.props.data });
  }

  render() {
    return (
      <ResponsiveContainer width="100%" height="80%">
        <LineChart data={this.state.data} />
      </ResponsiveContainer>
    );
  }

}
```

Unfortunately it doesn't work properly. What does work is the "dots" show up, but no animation, and if I set their color to red, they remain the default white. My workaround was to set a timeout of about 2 seconds before setting the state and updating the data variable, but it's far too hacky :(

**Comment by mario-jerkovic** [comment]
I have just tried to initial render component with state `data = null` and after the component is mounted just to simulate async request `setState` after 3 seconds and component renders correctly.
```javascript
class LinearGraph extends React.Component {

  state = {
    data: null,
  };

  componentDidMount() {
        setTimeout(() => {
              this.setState(() => ({ data }));
       }, 3000);
   }
   
   render() {
         return (
               <RC2 data={this.state.data} type='line' />
         );
   }
```

Are you sure that the `this.props.data` that you pass dow in the `LinearGraph` component is an `Object` with `labels` and `datasets` keys and that `ResponsiveContainer` compoments does not influence re-rendering of the child components. Maybe if you can share the code or create small demo we could figure this out :)
